# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./docker-volume/db-data-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edge_authorization_server
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - local_app_net
  
networks:
  local_app_net:
    driver: bridge
