name: Go Checkstyle
on:
  pull_request_target:
    types: [labeled, opened, synchronize, reopened]
    paths-ignore:
      - "service/**"

permissions:
  contents: read

jobs:
  go-checkstyle:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
    steps:
      - run: 'echo "Step is not required!"'
