name: Go Build and Test
on:
  pull_request_target:
    types: [labeled, opened, synchronize, reopened]
    paths-ignore:
      - "service/**"

permissions:
  contents: read

jobs:
  go-compile-and-test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            go-version: [ '1.23', '1.24' ]
    steps:
      - run: 'echo "Step is not required!"'
